---
title: "ABE - extended methods"
bibliography: 'references/library.bib'
csl: 'format/cell.csl'
output:
  word_document:
    reference_docx: 'format/template.docx'
    pandoc_args: '--smart'
params:
  # What sections should be re-executed?
  data: no
  analyses: no
  figures: no
---

<!--- README ----
Use rmarkdown::render('01-Main.Rmd') to compile this report

Keep Main.Rmd as simple as possible. It should just contain author information,
a summary of this document, and an outline of the document structure.

Save data to data directory. Save figures to figure directory. Include figures
from pre-compiled versions to speed up document compilation and to make the 
figures directory the primary source of figures for this document.

Reference literature using @citekey or [@citekey] using citekeys in 
references/library.bib (BibTex format reference library)

Note that fourth level header (i.e. ####) is defined as a first level header 
with a page break in the format/template.docx word template.
--->

__Eric Bryant__^1^, __Pierre Billon__^2^, and __Alberto Ciccia__^2,3,\*^ 

> ^1^ Department of Biological Sciences, Columbia University, New York, NY, USA \
> ^2^ Department of Genetics & Development, Columbia University Medical Center, New York, NY, USA \
> ^3^ Lead Contact \
> ^\*^ Correspondence: <ac3685@columbia.edu>

# SUMMARY

**ABE makes A to G changes ... fill in the background**

<!--- Page Break --->
#### INSTALL

```{r child = '02-Install.Rmd'}
```

<!--- Page Break --->
#### DATA

```{r child = '03-Data.Rmd'}
```

<!--- Page Break --->
#### ANALYSIS

```{r child = '04-Analysis.Rmd'}
```

<!--- Page Break --->
#### FIGURES

```{r child = '05-Figures.Rmd'}
```

<!--- Page Break --->
#### SESSION INFORMATION 

```{r eval = TRUE, echo = FALSE, message = TRUE, comment = ''}
.Rprofile$load_requirements(show_loaded = TRUE)
```

<!--- Page Break --->
#### REFERENCES
